# Generated by Django 2.2 on 2023-05-05 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'db_table': 'Grocery',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='userregistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=500)),
                ('Country', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'userregistration',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Grocery')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.login')),
            ],
        ),
    ]
