# Generated by Django 2.2 on 2023-05-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='user',
        ),
    ]
